### PR TITLE
Make correction UI work with TPL imagery

### LINKED ISSUE #26: Location correction broken for TPL images
image

### PR DESCRIPTION
**Pull request by danvk**
image

Fixes #26

### CODE REVIEW

File: oldto-site/js/fill-details.js [hunk 1]
```diff
@@ -0,0 +1,33 @@
...
+  'creator', 'description', 'subject' // TPL
+];
+
+export function fillDetailsPanel(photoId, info, $pane) {
+  const {archives_fields, geocode, url, tpl_fields} = info;
+  const source = tpl_fields ? 'tpl' : 'toronto-archives';
+
+  $pane.find('a.link').attr('href', url);
+  $pane.find('a.link.source')
+    .text(source === 'tpl' ? 'Toronto Public Library' : 'City of Toronto Archives');
```
Comment (californianseabass) [inline oldto-site/js/fill-details.js]: put line 12 in here, unless you thinks its a big readability win, or the source variable gets used elsewhere

Comment (danvk) [reply oldto-site/js/fill-details.js]: done
